name = "voice2text"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[ai]
binding = "AI"

[vars]
CORRECT_TERMS = '''
[
  "引体向上",
  "负重",
  "俯卧",
  "撑",
  "杠铃",
  "上斜",
  "哑铃",
  "卧推",
  "深蹲",
  "硬拉",
  "划船",
  "弯举",
  "臂",
  "推",
  "举",
  "肩",
  "坐姿",
  "高位",
  "下拉",
  "高位",
  "侧",
  "平举",
  "腿",
  "屈伸",
  "俯卧",
  "腿屈伸",
  "仰卧",
  "飞鸟",
  "卷腹",
  "平板",
  "支撑",
  "公斤",
  "次",
  "组"
]
'''
