name = "voice-to-text-api"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[ai]
binding = "AI"

[vars]
CORRECT_TERMS = '''
[
  "引体向上",
  "负重",
  "俯卧撑",
  "杠铃卧推",
  "哑铃卧推",
  "深蹲",
  "硬拉",
  "划船",
  "弯举",
  "臂屈伸",
  "卷腹",
  "平板支撑",
  "公斤",
  "次",
  "组"
]
'''
